FROM node:12.13-alpine
LABEL maintainer="DJANGO CELERY <nga@atolcd.com>"

# Create app directory
WORKDIR /local_modules

# Install app dependencies
COPY frontend/package*.json /local_modules/

RUN npm i
RUN npm install -g npm-check
RUN npm install -g @vue/cli

WORKDIR /app

# Bundle app source
COPY frontend/ /app/
COPY frontend/ /local_modules/
